# Generated by Django 5.2.13 on 2026-04-28 02:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_organization_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("site_label", models.CharField(blank=True, max_length=200)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "coordinator",
                    models.ForeignKey(
                        limit_choices_to={"role": "coordinator"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coordinated_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facilitators",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "facilitator"},
                        related_name="facilitated_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="programs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="core.program",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "scheduled_date"), name="unique_session_per_program_date"
                    )
                ],
            },
        ),
    ]
