# Generated by Django 5.2.13 on 2026-05-29 13:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def _make_slug(name, qs):
    base = slugify(name) or "item"
    slug = base
    n = 1
    while qs.filter(slug=slug).exists():
        n += 1
        slug = f"{base}-{n}"
    return slug


def backfill_slugs(apps, schema_editor):
    Organization = apps.get_model("core", "Organization")
    Program = apps.get_model("core", "Program")
    for org in Organization.objects.filter(slug=""):
        org.slug = _make_slug(org.name, Organization.objects)
        org.save(update_fields=["slug"])
    for prog in Program.objects.filter(slug=""):
        prog.slug = _make_slug(prog.name, Program.objects)
        prog.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_program_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name="program",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(backfill_slugs, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name="ProfileSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="core.program",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="core.profilesnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "version"), name="unique_snapshot_version_per_program"
                    )
                ],
            },
        ),
    ]
