# Generated by Django 5.2.13 on 2026-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                ("content_sha", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("fetch_url", models.URLField(max_length=2048)),
                ("fetched_at", models.DateTimeField(db_index=True)),
                ("source_id", models.CharField(db_index=True, max_length=64)),
                ("mime_type", models.CharField(max_length=128)),
                ("content_ref", models.CharField(max_length=512)),
                ("http_status", models.IntegerField()),
                ("fetch_metadata", models.JSONField(default=dict)),
            ],
        ),
    ]
