# Generated by Django 5.2.13 on 2026-05-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("seen", "Seen"),
                            ("funder_upserted", "Funder upserted"),
                            ("funder_enriched", "Funder enriched"),
                            ("historical_grant_recorded", "Historical grant recorded"),
                            ("resolved", "Resolved"),
                            ("merged", "Merged"),
                            ("split", "Split"),
                            ("status_changed", "Status changed"),
                            ("withdrawn", "Withdrawn"),
                            ("parse_failed", "Parse failed"),
                            ("robots_blocked", "Robots blocked"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(db_index=True, max_length=64)),
                (
                    "content_sha",
                    models.CharField(blank=True, db_index=True, max_length=64, null=True),
                ),
                ("opportunity_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("funder_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("program_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                ("actor", models.CharField(max_length=128)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_id", "timestamp"], name="grants_inge_source__0d14c2_idx"
                    ),
                    models.Index(
                        fields=["opportunity_id", "timestamp"],
                        name="grants_inge_opportu_6dfe96_idx",
                    ),
                ],
            },
        ),
    ]
