# Generated by Django 5.2.13 on 2026-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0002_corpusevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="corpusevent",
            name="content_sha",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
