# Generated by Django 5.2.13 on 2026-05-18 17:33

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0003_alter_corpusevent_content_sha"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ein",
                    models.CharField(
                        blank=True, db_index=True, max_length=9, null=True, unique=True
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                ("canonical_name_normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "funder_type",
                    models.CharField(
                        choices=[
                            ("private_foundation", "Private Foundation"),
                            ("community_foundation", "Community Foundation"),
                            ("public_charity", "Public Charity"),
                            ("govt_federal", "Federal Government"),
                            ("govt_state", "State Government"),
                            ("govt_local", "Local Government"),
                            ("corporate", "Corporate"),
                            ("united_way", "United Way"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("accepts_unsolicited", models.BooleanField(blank=True, null=True)),
                (
                    "typical_award_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "typical_award_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("notes", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                ("canonical_name_normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "funder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="grants_ingest.funder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FunderAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.CharField(max_length=255)),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "funder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="grants_ingest.funder",
                    ),
                ),
            ],
            options={
                "unique_together": {("funder", "normalized")},
            },
        ),
        migrations.CreateModel(
            name="ProgramAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.CharField(max_length=255)),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="grants_ingest.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "normalized")},
            },
        ),
    ]
