# Generated by Django 5.2.13 on 2026-05-18 23:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0004_funder_program_funderalias_programalias"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("funder_ein", models.CharField(db_index=True, max_length=9)),
                ("tax_year", models.IntegerField(db_index=True)),
                ("recipient_name_raw", models.CharField(max_length=512)),
                ("recipient_address_raw", models.TextField(blank=True, default="")),
                (
                    "recipient_ein",
                    models.CharField(blank=True, db_index=True, default="", max_length=9),
                ),
                ("recipient_id", models.UUIDField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("purpose", models.TextField(blank=True, default="")),
                ("relationship_flag", models.CharField(blank=True, default="", max_length=64)),
                (
                    "funder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_grants",
                        to="grants_ingest.funder",
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historical_grants",
                        to="grants_ingest.rawrecord",
                    ),
                ),
            ],
            options={
                "unique_together": {("source_record", "recipient_name_raw", "amount", "tax_year")},
            },
        ),
    ]
