# Generated by Django 5.2.13 on 2026-05-18 23:12

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0005_historicalgrant"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorpusSnapshot",
            fields=[
                ("tag", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("event_log_position", models.BigIntegerField()),
                ("object_store_manifest_ref", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="IngestHealthSnapshot",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("captured_at", models.DateTimeField(db_index=True)),
                ("source_id", models.CharField(db_index=True, max_length=64)),
                ("metric", models.CharField(max_length=64)),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("alert_threshold_breached", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OpportunityInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("application_open_at", models.DateTimeField(blank=True, null=True)),
                ("application_close_at", models.DateTimeField(blank=True, null=True)),
                ("rolling", models.BooleanField(default=False)),
                (
                    "award_min",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "award_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "typical_award",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "total_pool",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("capacity", "Capacity"),
                            ("operating", "Operating"),
                            ("scholarship", "Scholarship"),
                            ("capital", "Capital"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                ("eligibility", models.JSONField(default=dict)),
                ("geographic_scope", models.JSONField(default=dict)),
                ("subject_areas", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("upcoming", "Upcoming"),
                            ("closed", "Closed"),
                            ("rolling", "Rolling"),
                            ("unreachable", "Unreachable"),
                            ("provisionally_withdrawn", "Provisionally Withdrawn"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="open",
                        max_length=32,
                    ),
                ),
                ("first_seen_at", models.DateTimeField()),
                ("last_seen_at", models.DateTimeField()),
                (
                    "extraction_model_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("schema_version", models.CharField(blank=True, default="", max_length=32)),
                ("provenance", models.JSONField(default=dict)),
                (
                    "funder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="grants_ingest.funder",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="grants_ingest.program",
                    ),
                ),
                (
                    "source_records",
                    models.ManyToManyField(
                        blank=True, related_name="opportunities", to="grants_ingest.rawrecord"
                    ),
                ),
            ],
        ),
    ]
