# Generated by Django 5.2.13 on 2026-05-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grants_ingest", "0006_corpussnapshot_ingesthealthsnapshot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunityinstance",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="opportunityinstance",
            name="funder_name_raw",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="opportunityinstance",
            name="notes",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="opportunityinstance",
            name="source_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="corpusevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("seen", "Seen"),
                    ("funder_upserted", "Funder upserted"),
                    ("funder_enriched", "Funder enriched"),
                    ("historical_grant_recorded", "Historical grant recorded"),
                    ("resolved", "Resolved"),
                    ("merged", "Merged"),
                    ("split", "Split"),
                    ("status_changed", "Status changed"),
                    ("withdrawn", "Withdrawn"),
                    ("parse_failed", "Parse failed"),
                    ("robots_blocked", "Robots blocked"),
                    ("opportunity_seen", "Opportunity seen"),
                    ("opportunity_updated", "Opportunity updated"),
                    ("opportunity_filtered", "Opportunity filtered"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="opportunityinstance",
            unique_together={("source_id", "external_id")},
        ),
    ]
