from django import forms

from core.models import Program


class ProgramCreateForm(forms.ModelForm):
    """Coordinator-facing program setup — the 30-second onboarding step.

    Org and coordinator are taken from the logged-in user, never chosen here,
    so a coordinator can only create programs inside their own org. Slug is
    auto-generated by Program.save().
    """

    class Meta:
        model = Program
        fields = ["name", "summary", "site_label"]
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "e.g. After-School Peace Club"}),
            "summary": forms.Textarea(
                attrs={"rows": 3, "placeholder": "One or two sentences a donor would read."}
            ),
            "site_label": forms.TextInput(
                attrs={"placeholder": "e.g. Riverdale Community Center (optional)"}
            ),
        }
        labels = {
            "name": "Program name",
            "summary": "Short description",
            "site_label": "Site / location",
        }
